### PR TITLE
README for network layer

### PR DESCRIPTION
**Pull request by saum-g**

### CODE REVIEW

**Comment by BassemSafieldeen** [comment]
This is nice, thanks :) 
I have some comments that I will write down shortly.

**Comment by BassemSafieldeen** [comment]
Ok, let's start with the most obvious thing (in my opinion). In the section "Path Discovery" you mention two different ways of discovering the repeater path between two end-nodes. Doesn't it make sense to move this information to the README's of two different protocols?

**Comment by saum-g** [comment]
We could do that. But it might look odd to only have a readme in a folder. Since I was looking forward to a more analytical approach to the problem here. Look at existing protocols, make new ones, finalise upon the most optimal one(s) and then implementation. 

We can of course make this change now and revert it if we don't like it

**Comment by BassemSafieldeen** [comment]
I think I see what you mean. But it won't be just a README because I will add some placeholder Lean code right away, actually --- to formalize the math in the papers.

**Comment by saum-g** [comment]
Oh! Let's do it then. I'll make the changes to the folder and append the commit to the pull request. Meanwhile we can discuss any other changes you have in mind

**Comment by BassemSafieldeen** [comment]
The "Link Layer interface" should be moved to the README of the Link Layer, no? As it stands, this section might be redundant if we add a similar README in the Link Layer folder.

**Comment by saum-g** [comment]
I think keeping the details of the functions will help us avoid asking too much or too less of the link layer. If you say I can add the descriptions of the functions to the link layer README and just keep the function titles in the current one. 

Also what should we do about the third point in the link layer interface I have mentioned? It is unclear to me which layer's job it should be

**Comment by BassemSafieldeen** [comment]
> I think keeping the details of the functions will help us avoid asking too much or too less of the link layer. If you say I can add the descriptions of the functions to the link layer README and just keep the function titles in the current one.

Sure, let's try it your way.

> Also what should we do about the third point in the link layer interface I have mentioned? It is unclear to me which layer's job it should be

What I had in mind is this: Each node (link layer) keeps track of what happens with its qubits and notifies the network layer.

**Comment by saum-g** [comment]
Hi @BassemSafieldeen . I have pushed the required changes to my branch and updated the pull request. Could you please check if this is fine?

**Comment by BassemSafieldeen** [comment]
Hi @saum-g , welcome back :) I will review our conversation and respond shortly.

**Pull request merged**
