### PR TITLE
Add pseudocode for BB84

### PR DESCRIPTION
**Pull request by saum-g**

### CODE REVIEW

**Comment by BassemSafieldeen** [comment]
Why add the pseudo code as images? Why not as code blocks in the BB84.md files?

**Comment by saum-g** [comment]
I was not able to write latex code in the markdown document, so I did something similar to that in the Transport Layer folder.

**Comment by BassemSafieldeen** [comment]
Hmmm, I see...Ok, let's do it like that for now. Please revert that last commit and bring back the image.

**Comment by saum-g** [comment]
Done

**Pull request merged**
